data_and_forms/urls.py
from django.urls import path

from . import views

app_name = "crud"

urlpatterns = [
    path('', views.Index.as_view(), name='index'),
    path('add/', views.AddUser.as_view(), name='add'),
    path('delete/<pk>', views.DeleteUser.as_view(), name = "delete"),
    path('edit/<pk>', views.EditUser.as_view(), name = "edit"),
]

testytesterson/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('test/', include('data_and_forms.urls')),
    path('admin/', admin.site.urls),
]

data_and_forms/models.py
from django.db import models
from django.core.exceptions import ValidationError
from django.core.validators import MaxValueValidator, MinValueValidator, MaxLengthValidator, MinLengthValidator
from django.urls import reverse

# Create your models here.
class User(models.Model):
    Name = models.CharField(max_length = 50, validators=[MaxLengthValidator(50), MinLengthValidator(8)])
    Position = models.CharField(max_length = 50)
    Office = models.CharField(max_length = 50)
    Age = models.IntegerField(validators=[MinValueValidator(13)])

    def __str__(self):
        return self.Name

    def get_absolute_url(self):
        return reverse("crud:index") 

data_and_forms/views.py
from django.views import generic, View
from django.views.generic import CreateView, DeleteView, UpdateView, RedirectView
from .models import User
from django.urls import reverse_lazy

class Index(generic.ListView):
    template_name = 'users.html'

    def get_queryset(self):
        return User.objects.all()

class AddUser(CreateView):
    model = User
    fields = ['Name', 'Position', "Age", "Office"]
    template_name = 'user_form.html'

    def form_valid(self, form):
        return super(AddUser, self).form_valid(form)

class EditUser(UpdateView):
    model = User
    template_name = "user_edit.html"
    fields = ['Name', 'Position', "Age", "Office"]

    def form_valid(self, form):
        return super(EditUser, self).form_valid(form)

class DeleteUser(DeleteView):
    model = User
    success_url = reverse_lazy('crud:index')

data_and_forms/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    
    <meta charset="UTF-8">
    <meta name="description" content="">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- The above 4 meta tags *must* come first in the head; any other head content must come *after* these tags -->

    
    <!-- Title -->
    <title>Home</title>

    
    {% load static %}
    <!-- Favicon -->
    <link rel="icon" href="{% static 'img/core-img/favicon.ico' %}">

    <!-- Bootstrap -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdn.datatables.net/1.11.5/css/jquery.dataTables.min.css">
    

    <!-- Core Stylesheet -->
    <link href="{% static 'style.css' %}" rel="stylesheet">

    <!-- Responsive CSS -->
    <link href="{% static 'css/responsive/responsive.css' %}" rel="stylesheet">

    
    

</head>

<body>
    <!-- ****** Header Area Start ****** -->
    <header class="header_area">
        <div class="container">
            <div class="row">
                <!-- Logo Area Start -->
                <div class="col-12 section_padding_100 ">
                    <div class="logo_area text-center">
                        <a href="#" class="yummy-logo"> {% block title %}CRUD app{% endblock title %}</a> 
                        
                    </div>
                    <div class="text-center">
                        <a href="{% url 'crud:add' %}" class="text-center"> <h4> Create user </h4> </a>
                    </div>
                </div>
            </div>
    </header>
    <!-- ****** Header Area End ****** -->

    {% block body %}
    {% endblock body %}


    <!-- Jquery-2.2.4 js -->
    <script src="{% static 'js/jquery/jquery-2.2.4.min.js' %}"></script>
    <script src="https://cdn.datatables.net/1.11.5/js/jquery.dataTables.min.js"></script>
    <!-- Popper js -->
    <script src="{% static 'js/bootstrap/popper.min.js' %}"></script>
    <!-- Bootstrap-4 js -->
    <script src="{% static 'js/bootstrap/bootstrap.min.js' %}"></script>
    <!-- All Plugins JS -->
    <script src="{% static 'js/others/plugins.js' %}"></script>
    <!-- Active JS -->
    <script src="{% static 'js/active.js' %}"></script>
    {% block script %}
    {% endblock script %}

</body>

data_and_forms/templates/user_edit.html
{% extends "base.html" %}

{% block body%}
<div class = "container-field">

    <div class="text-center"><h1><strong>Edit user</strong></h1></div>
    <br><br>
    <div class = "row">
        
        <div class = "col-md-4 col-md-offset-4">
                    <form  action="" method="POST" enctype="multipart/form-data">
                        {% csrf_token %}

                        {% for field in form %}
                            <div class="fieldWrapper">
                                {{ field.errors }}
                                {{ field.label_tag }} {{ field }}
                                {% if field.help_text %}
                                <p class="help">{{ field.help_text|safe }}</p>
                                {% endif %}
                            </div>
                        {% endfor %}

                        <div class = "form-horizontal">
                            <div class="text-center">
                                <button type="submit" class="btn contact-btn">Submit</button>
                            </div>  
                        </div>
                    </form>
        </div>

    </div>

</div>
{% endblock %}
{% block script %}


{% endblock script %}

data_and_forms/templates/user_form.html
{% extends "base.html" %}

{% block body%}
<div class = "container-field">
        <div class="text-center"><h1><strong>Add user</strong></h1></div>
        <br><br>
    <div class = "row">
        
        <div class = "col-md-4 col-md-offset-4">
                    <form  action="" method="POST" enctype="multipart/form-data">
                        {% csrf_token %}

                        {% for field in form %}
                            <div class="fieldWrapper">
                                {{ field.errors }}
                                {{ field.label_tag }} {{ field }}
                                {% if field.help_text %}
                                <p class="help">{{ field.help_text|safe }}</p>
                                {% endif %}
                            </div>
                        {% endfor %}
                        <div class = "form-horizontal">
                            <div class="text-center">
                                <button type="submit" class="btn contact-btn">Submit</button>
                            </div>    
                        </div>
                    </form>
        </div>

    </div>

</div>
{% endblock %}

data_and_forms/templates/users.html
{% extends "base.html" %}

{% block body%}
<div class = "container-field">
    <div class="container">
        <div class="row">
            {% csrf_token %}
            <table id="myTable" class="display text-center">
                <thead>
                    <tr>
                        <th>Name</th>
                        <th>Age</th>
                        <th>Position</th>
                        <th>Office</th>
                        <th>Actions</th>
                    </tr>
                </thead>
                <tbody>
                    {% for user in object_list %}
                    <tr id="user-{{user.id}}">
                        <td>{{ user.Name }}</td>
                        <td>{{ user.Age }} </td>
                        <td>{{ user.Position }}</td>
                        <td>{{ user.Office }} </td>
                        <td>
                        <a href="{% url 'crud:edit' user.id%}" class="text-center">  Edit  </a> 
                        , 
                        <button type="button" class="btn btn-delete" data-toggle="modal" data-target="#user-{{user.id}}">
                            Delete
                        </button>
                    </tr>
                    <!-- Modal -->
                        <div class="modal fade" id="user-{{user.id}}" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
                            <div class="modal-dialog" role="document">
                                <div class="modal-content">
                                    <div class="modal-header">
                                        <h5 class="modal-title" id="exampleModalLabel">Delete user {{user.Name}}?</h5>
                                        </button>
                                    </div>
                                    <div class="modal-body">
                                        This process cannot be undone.
                                    </div>
                                    <div class="modal-footer">
                                        <form action="{% url 'crud:delete' user.id %}" method="post" visible = "off">
                                            {% csrf_token %}
                                            <div class="text-center">
                                                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                                                <button type="submit" class="btn btn-danger">Delete user</button>
                                            </div>
                                        </form>
                                    </div>
                                </div>
                            </div>
                        </div>
                        </td>
                    {% endfor %}
                </tbody>
            </table>
            
        </div>
    </div>
</div>

{% endblock %}

{% block script %}
    {% load static %}
    <script src="{% static 'js/datatables.js' %}"></script>
{% endblock %}